app/models/loyalty.py
#loyalty.py
from app import db
from datetime import datetime

class LoyaltyProgram(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    description = db.Column(db.String(255), nullable=True)
    points = db.Column(db.Float, default=0.0)
    points_rp = db.Column(db.Float, default=0.0) #
    points_active = db.Column(db.Boolean, default=True)
    discount = db.Column(db.Float, default=0.0)
    discount_type = db.Column(db.Float, default=0.0) #('1', 'Persen'), ('2', 'Rupiah'), ('3', 'Gratis')
    discount_repeat_number = db.Column(db.Integer, nullable=True, default=1)
    discount_repeat = db.Column(db.Boolean, default=True)
    discount_active = db.Column(db.Boolean, default=True)
    is_active = db.Column(db.Boolean, default=True)
    is_newcustomer = db.Column(db.Boolean, default=True)
    is_oldcustomer = db.Column(db.Boolean, default=True)
    start_date = db.Column(db.DateTime, nullable=True)
    end_date = db.Column(db.DateTime, nullable=True)
    created_date = db.Column(db.DateTime, default=datetime.utcnow)
    updated_date = db.Column(db.DateTime, onupdate=datetime.utcnow)
    # Relationship
    tiers = db.relationship('LoyaltyTier', backref='loyalty_program', lazy=True)  
    
    @property
    def campaigns(self):
        from app.models.campaign import Campaign
        return db.relationship('Campaign', backref='loyalty_program', lazy=True)

class LoyaltyTier(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    program_id = db.Column(db.Integer, db.ForeignKey('loyalty_program.id', ondelete='CASCADE'), nullable=False)
    name = db.Column(db.String(50), nullable=False)
    points_threshold = db.Column(db.Integer, nullable=False)  
    benefits = db.Column(db.String(255), nullable=True)
    created_date = db.Column(db.DateTime, default=datetime.utcnow)
    updated_date = db.Column(db.DateTime, onupdate=datetime.utcnow)

class CustomerLoyalty(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    customer_id = db.Column(db.Integer, db.ForeignKey('customer.id'), nullable=False)
    program_id = db.Column(db.Integer, db.ForeignKey('loyalty_program.id'), nullable=False)  
    tier_id = db.Column(db.Integer, db.ForeignKey('loyalty_tier.id'), nullable=True)
    total_points_earned = db.Column(db.Float, nullable=True, default=0.0)
    total_points_used = db.Column(db.Float, nullable=True, default=0.0)
    created_date = db.Column(db.DateTime, default=datetime.utcnow)
    updated_date = db.Column(db.DateTime, onupdate=datetime.utcnow)
    
class ReferralProgram(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    program_id = db.Column(db.Integer, db.ForeignKey('loyalty_program.id'), nullable=False)
    referrer_id = db.Column(db.Integer, db.ForeignKey('customer.id'), nullable=False)
    referee_id = db.Column(db.Integer, db.ForeignKey('customer.id'), nullable=False)
    reward_points = db.Column(db.Integer, default=0)
    created_date = db.Column(db.DateTime, default=datetime.utcnow)

app/forms/loyalty.py
# forms/loyalty.py
from flask_wtf import FlaskForm
from wtforms import DateField, HiddenField, TextAreaField, StringField, IntegerField, FloatField, BooleanField, SelectField, SubmitField
from wtforms.validators import DataRequired, Optional

class LoyaltyProgramForm(FlaskForm):
    name = StringField('Program Name', validators=[DataRequired()])
    description = StringField('Program Description', validators=[Optional()])
    points_active = BooleanField(
        'Activate Point Reward',
        default=True
    )
    points = IntegerField('Points Given For Purchases Multiples of USD ', validators=[Optional()])
    points_rp = IntegerField('Point Value in USD', validators=[Optional()])
    discount = FloatField('Discount Amount Given (% or Rp Amount)', validators=[Optional()])
    start_date = DateField('Start Date', validators=[DataRequired()])
    end_date = DateField('End Date', validators=[DataRequired()]) 
    discount_type = SelectField(
        'Discount Type',
        choices=[('1', 'Percent'), ('2', 'USD'), ('3', 'Free')],
        validators=[Optional()]
    )
    discount_repeat_number = IntegerField(
        'Discount given for transactions in multiples of ',
        validators=[Optional()],
        default=1
    )
    discount_repeat = BooleanField(
        'Discount given repeatedly for every multiple',
        default=True
    )
    discount_points = BooleanField(
        'Activate Discount Rewards',
        default=True
    )
    is_active = BooleanField('Active', default=True)
    is_newcustomer = BooleanField('New Customer', default=True)
    is_oldcustomer = BooleanField('Existing Customer', default=True)
    submit = SubmitField('Create Program')


class LoyaltyTierForm(FlaskForm):
    name = StringField('Tier Name', validators=[DataRequired()])
    points_threshold = IntegerField('Point Threshold (Minimum)', validators=[DataRequired()])
    benefits = TextAreaField('Tier Benefits', validators=[Optional()])
    program_id = SelectField('Loyalty Program', coerce=int, validators=[DataRequired()])
    submit = SubmitField('Save Tier')


class DeleteTierForm(FlaskForm):
    tier_id = HiddenField('Tier ID')
    submit = SubmitField('Delete')
    
    
class DeleteLoyaltyProgramForm(FlaskForm):
    program_id = HiddenField('Program ID')
    submit = SubmitField('Delete')

app/routes/loyalty.py
# routes/loyalty.py
from flask_wtf import FlaskForm
from flask import Blueprint, render_template, redirect, url_for, flash, request, jsonify
from app import db
from app.models.loyalty import LoyaltyProgram, LoyaltyTier
from app.forms.loyalty import LoyaltyProgramForm, LoyaltyTierForm, DeleteTierForm,  DeleteLoyaltyProgramForm

loyalty = Blueprint('loyalty', __name__)

@loyalty.route('/loyalty/programs', methods=['GET'])
def list_programs():
    programs = LoyaltyProgram.query.all()
    form = DeleteLoyaltyProgramForm()
    return render_template('loyalty/list_loyalty.html', programs=programs,form=form)


@loyalty.route('/loyalty/program/add', methods=['GET', 'POST'])
def add_program():
    form = LoyaltyProgramForm()
    if form.validate_on_submit():
        new_program = LoyaltyProgram(
            name=form.name.data,
            description=form.description.data,
            points=form.points.data,
            points_rp=form.points_rp.data,
            points_active=form.points_active.data,
            discount=form.discount.data,
            discount_type=int(form.discount_type.data),
            discount_repeat_number=form.discount_repeat_number.data,
            discount_repeat=form.discount_repeat.data,
            discount_points=form.discount_points.data,
            is_active=form.is_active.data,
            is_newcustomer = form.is_newcustomer.data,
            is_oldcustomer = form.is_newcustomer.data,
            start_date=form.start_date.data,
            end_date=form.end_date.data
        )
        db.session.add(new_program)
        db.session.commit()
        flash('Loyalty added!', 'success')
        return redirect(url_for('loyalty.list_programs'))
    
    return render_template('loyalty/add_loyalty_program.html', form=form)


@loyalty.route('/loyalty/program/edit/<int:id>', methods=['GET', 'POST'])
def update_program(id):
    program = LoyaltyProgram.query.get_or_404(id)
    form = LoyaltyProgramForm(obj=program)
    
    if form.validate_on_submit():
        program.name = form.name.data
        program.description = form.description.data
        program.points = form.points.data
        program.points_rp=form.points_rp.data
        program.points_active=form.points_active.data
        program.discount = form.discount.data
        program.discount_type = int(form.discount_type.data)
        program.discount_repeat_number = form.discount_repeat_number.data
        program.discount_repeat = form.discount_repeat.data
        program.discount_points = form.discount_points.data
        program.is_active=form.is_active.data
        program.is_newcustomer = form.is_newcustomer.data
        program.is_oldcustomer = form.is_newcustomer.data
        program.start_date=form.start_date.data
        program.end_date=form.end_date.data
        db.session.commit()
        #flash('Loyalty updated!', 'success')
        return redirect(url_for('loyalty.list_programs'))
    
    return render_template('loyalty/add_loyalty_program.html', form=form)


@loyalty.route('/loyalty/program/delete/<int:id>', methods=['POST'])
def delete_program(id):
    form = DeleteLoyaltyProgramForm()
    if form.validate_on_submit():
        program = LoyaltyProgram.query.get_or_404(id)
        if program :
            db.session.delete(program)
            db.session.commit()
        #flash('Loyalty deleted!', 'success')
    return redirect(url_for('loyalty.list_programs'))

@loyalty.route('/loyalty/tiers', methods=['GET'])
def list_tiers():

    tiers = db.session.query(LoyaltyTier, LoyaltyProgram) \
            .join(LoyaltyProgram, LoyaltyTier.program_id == LoyaltyProgram.id).all()
    form = DeleteTierForm()
    return render_template('loyalty/list_tiers.html', tiers=tiers,form=form)

@loyalty.route('/loyalty/tier/add', methods=['GET', 'POST'])
def add_tier():
    form = LoyaltyTierForm()
    form.program_id.choices = [(p.id, p.name) for p in LoyaltyProgram.query.filter_by(company_id=current_user.company_id).all()]

    if form.validate_on_submit():
        new_tier = LoyaltyTier(
            name=form.name.data,
            points_threshold=form.points_threshold.data,
            benefits=form.benefits.data,
            program_id=form.program_id.data
        )
        db.session.add(new_tier)
        db.session.commit()
        flash('Loyalty Tier added!', 'success')
        return redirect(url_for('loyalty.list_tiers'))
    
    return render_template('loyalty/add_tier.html', form=form)


@loyalty.route('/loyalty/tier/edit/<int:id>', methods=['GET', 'POST'])
def edit_tier(id):
    tier = LoyaltyTier.query.get_or_404(id)
    form = LoyaltyTierForm(obj=tier)
    form.program_id.choices = [(p.id, p.name) for p in LoyaltyProgram.query.all()]

    if form.validate_on_submit():
        tier.name = form.name.data
        tier.points_threshold = form.points_threshold.data
        tier.benefits = form.benefits.data
        tier.program_id = form.program_id.data
        db.session.commit()
        flash('Loyalty Tier updated!', 'success')
        return redirect(url_for('loyalty.list_tiers'))
    
    return render_template('loyalty/add_tier.html', form=form)


@loyalty.route('/loyalty/tier/delete/<int:id>', methods=['POST'])
def delete_tier(id):
    form = DeleteTierForm()
    if form.validate_on_submit():
        tier = LoyaltyTier.query.get_or_404(id)
        if tier: 
            db.session.delete(tier)
            db.session.commit()
            flash('Loyalty Tier deleted!', 'success')
    return redirect(url_for('loyalty.list_tiers'))

app/templates/loyalty/add_loyalty_program.html
{% extends "advancecrm/basedetail.html" %}
{% block title %}Loyalty Program{% endblock %}
{% block content %}

<div class="container py-4">
    <div class="row justify-content-center">
        <div class="col-lg-12">
            <div class="card shadow-lg">
                <div class="card-header bg-primary text-white">
                    <h5 class="mb-0 text-white">Add Program</h5>
                </div>
                <div class="card-body">
                    <!-- Display Form Errors -->
                    {% if form.errors %}
                    <div class="alert alert-danger">
                        <ul class="mb-0">
                            {% for field, errors in form.errors.items() %}
                                {% for error in errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                    {% endif %}
                    
                    <form method="POST" action="">
                        {{ form.hidden_tag() }}
                        
                        <!-- Program Name -->
                        <div class="form-group mb-3">
                            <label for="name" class="form-label">{{ form.name.label }} </label>
                            {{ form.name(class="form-control") }}
                        </div>
                        
                        <!-- Description -->
                        <div class="form-group mb-3">
                            <label for="description" class="form-label">{{ form.description.label }} </label>
                            {{ form.description(class="form-control") }}
                        </div>
                        <div class="form-group mb-3">
                            <label for="start_date">{{ form.start_date.label }}</label>
                            {{ form.start_date(class="form-control") }}
                        </div>
                        <div class="form-group mb-3">
                            <label for="end_date">{{ form.end_date.label }}</label>
                            {{ form.end_date(class="form-control") }}
                        </div>

                        <!-- Points Rewards -->
                        <div class="form-group mb-3">
                            <div class="form-check">
                                {{ form.points_active(class="form-check-input") }}
                                <label for="points_active" class="form-check-label">{{ form.points_active.label }} </label>
                            </div>
                        </div>
                        <div class="form-group mb-3">
                            <label for="points" class="form-label">{{ form.points.label }} </label>
                            {{ form.points(class="form-control") }}
                        </div>

                        <!-- Points -->
                        <div class="form-group mb-3">
                            <label for="points_rp" class="form-label">{{ form.points_rp.label }} </label>
                            {{ form.points_rp(class="form-control") }}
                        </div>
                        
                        <!-- Points-Based Discount -->
                        <div class="form-group mb-3">
                            <div class="form-check">
                                {{ form.discount_points(class="form-check-input") }}
                                <label for="discount_points" class="form-check-label">{{ form.discount_points.label }} </label>
                            </div>
                        </div>
                        <div class="form-group mb-3">
                            <label for="discount" class="form-label"> {{ form.discount.label }} </label>
                            {{ form.discount(class="form-control") }}
                        </div>

                        <!-- Discount Type -->
                        <div class="form-group mb-3">
                            <label for="discount_type" class="form-label"> {{ form.discount_type.label }} </label>
                            {{ form.discount_type(class="form-control") }}
                        </div>

                        <!-- Repeat Discount Number -->
                        <div class="form-group mb-3">
                            <label for="discount_repeat_number" class="form-label"> {{ form.discount_repeat_number.label }} </label>
                            {{ form.discount_repeat_number(class="form-control") }}
                        </div>

                        <!-- Repeat Discount Checkbox -->
                        <div class="form-group mb-3">
                            <div class="form-check">
                                {{ form.discount_repeat(class="form-check-input") }}
                                <label for="discount_repeat" class="form-check-label">{{ form.discount_repeat.label }} </label>
                            </div>
                        </div>

                        <div class="form-group mb-3">
                            <div class="form-check">
                                {{ form.is_newcustomer(class="form-check-input") }}
                                <label for="is_active" class="form-check-label">{{ form.is_newcustomer.label }} </label>
                            </div>
                        </div>
                        <div class="form-group mb-3">
                            <div class="form-check">
                                {{ form.is_oldcustomer(class="form-check-input") }}
                                <label for="is_active" class="form-check-label">{{ form.is_oldcustomer.label }} </label>
                            </div>
                        </div>
						
                        <!-- Is Active -->
                        <div class="form-group mb-3">
                            <div class="form-check">
                                {{ form.is_active(class="form-check-input") }}
                                <label for="is_active" class="form-check-label">{{ form.is_active.label }} </label>
                            </div>
                        </div>

                        <!-- Submit Button -->
                        <button class="btn btn-success w-100" type="submit">
                            <i class="fa-solid fa-floppy-disk"></i> Save
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/loyalty/add_tier.html
<!-- templates/loyalty/add_tier.html -->

{% extends "advancecrm/basedetail.html" %}
{% block title %}Loyalty Tier{% endblock %}
{% block content %}
<div class="container py-4">
    <div class="row justify-content-center">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="mb-0">Create Loyalty Tier</h5>
                </div>
                <div class="card-body">
                    <form method="POST" action="">
                        {{ form.hidden_tag() }}
                        <div class="form-group mb-3">
                            <label for="name">{{ form.name.label }}</label>
                            {{ form.name(class="form-control") }}
                        </div>
                        <div class="form-group mb-3">
                            <label for="points_threshold">{{ form.points_threshold.label }}</label>
                            {{ form.points_threshold(class="form-control") }}
                        </div>
                        <div class="form-group mb-3">
                            <label for="benefits">{{ form.benefits.label }}</label>
                            {{ form.benefits(class="form-control") }}
                        </div>
                        <div class="form-group mb-3">
                            <label for="program_id">{{ form.program_id.label }}</label>
                            {{ form.program_id(class="form-control") }}
                        </div>
                        <button type="submit" class="btn btn-success w-100">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/loyalty/list_loyalty.html
{% extends "advancecrm/basedetail.html" %}
{% block title %}Customer Loyalty Program{% endblock %}
{% block content %}

<div class="container py-4">
    <div class="d-flex justify-content-end mb-3">
        <a class="btn btn-danger d-flex align-items-center" id="addProgram" href="{{ url_for('loyalty.add_program') }}">
            <i class="fa-solid fa-heart-circle-plus"></i>&nbsp;Create Program
        </a> &nbsp;&nbsp;
        <a class="btn btn-warning d-flex align-items-center" id="adtier" href="{{ url_for('loyalty.list_tiers') }}">
            <i class="fa-solid fa-layer-group"></i>&nbsp;Tier Levels
        </a>&nbsp;&nbsp;
        <a class="btn btn-primary d-flex align-items-center" id="addProgram" href="{{ url_for('campaign.list_campaigns') }}">
            <i class="fa-solid fa-rectangle-ad"></i>&nbsp;Campaigns
        </a>
    </div>
    <div class="table-responsive">
         <table class="table table-hover table-striped">
             <thead class="sticky-header">
                <tr>
                    <th>Program Name</th>
                    <th>Points</th>
                    <th>Discount</th>
                    <th class="hide-on-mobile">Type</th>
                    <th>Multiples</th>
                    <th class="hide-on-mobile">Repeat</th>
                    <th class="hide-on-mobile">Points and Discount</th>
                    <th class="text-center">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for program in programs %}
                <tr>
                    <td>{{ program.name }}</td>
                    <td>{{ program.points }}</td>
                    <td>{{ program.discount }}</td>
                    <td class="hide-on-mobile">
                        {% if program.discount_type == 1 %}
                            Percent
                        {% elif program.discount_type == 2 %}
                            Rupiah
                        {% elif program.discount_type == 3 %}
                            Free
                        {% else %}
                            Unknown
                        {% endif %}
                    </td>
                    <td class="hide-on-mobile">{{ program.discount_repeat_number }}</td>
                    <td class="hide-on-mobile">
                        <input type="checkbox" {% if program.discount_repeat %}checked{% endif %} disabled>
                    </td>
                    <td>
                        <input type="checkbox" {% if program.discount_points %}checked{% endif %} disabled>
                    </td>
                    <td class="text-center">
                        <div class="d-inline-flex">
                            <!-- Edit Button -->
                            <a class="btn btn-warning btn-sm me-2" href="{{ url_for('loyalty.update_program', id=program.id) }}" title="Edit">
                                <i class="fa-regular fa-pen-to-square"></i>
                            </a>
                            <!-- Delete Form -->
                            <form method="POST" action="{{ url_for('loyalty.delete_program', id=program.id) }}" style="display:inline;" onsubmit="return confirm('Are you sure you want to delete this program?');">
                                {{ form.hidden_tag() }}
                                {{ form.program_id(id='program_id', value=program.id) }}
                                <button class="btn btn-danger btn-sm" type="submit" title="Delete">
                                    <i class="fa-regular fa-trash-can"></i>
                                </button>
                            </form>
                            <a class="btn btn-warning btn-sm me-2" href="{{ url_for('loyalty.list_tiers', id=program.id) }}" title="Tier Levels">
                                <i class="fa-solid fa-layer-group"></i>
                            </a>
                        </div>
                    </td>
                </tr>
                {% else %}
                <tr>
                    <td colspan="8" class="text-center text-muted">No programs available</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

app/templates/loyalty/list_tiers.html
<!-- templates/loyalty/list_tiers.html -->

{% extends "advancecrm/basedetail.html" %}
{% block title %}Loyalty Tier{% endblock %}
{% block content %}
<div class="container py-4">
    <div class="d-flex justify-content-end mb-3">
        <a class="btn btn-primary" href="{{ url_for('loyalty.add_tier') }}">
            <i class="fa-solid fa-plus me-2"></i>&nbsp;Add Loyalty Tier
        </a>
    </div>
    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Tier Name</th>
                    <th>Points Threshold</th>
                    <th>Benefits</th>
                    <th>Program</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for tier, program in tiers %}
                <tr>
                    <td>{{ tier.name }}</td>
                    <td>{{ tier.points_threshold }}</td>
                    <td>{{ tier.benefits }}</td>
                    <td>{{ program.name }}</td>
                    <td>
                        <a class="btn btn-warning btn-sm" href="{{ url_for('loyalty.edit_tier', id=tier.id) }}">Edit</a>
                        <form method="POST" action="{{ url_for('loyalty.delete_tier', id=tier.id) }}" style="display:inline;" onsubmit="return confirm('Are you sure you want to delete this tier?');">
                            {{ form.hidden_tag() }}
                            {{ form.tier_id(id='tier_id', value=tier.id) }}
                            <button class="btn btn-danger btn-sm" type="submit">Delete</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}